name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - 3DConsturctor-Intro/**
      - 3DConsturctor-Intro/mkdocs.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
        working-directory: ./3DConsturctor-Intro

      - name: Build MkDocs site
        run: mkdocs build --site-dir ../site
        working-directory: ./3DConsturctor-Intro

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-documents-${{ github.sha }}
          path: site/

  deploy:
    concurrency:
      group: github-pages
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-documents-${{ github.sha }}
          path: site

      - uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - id: deployment
        uses: actions/deploy-pages@v1