name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material
      working-directory: ./3DConsturctor-Intro

    - name: Build MkDocs site
      run: mkdocs build --site-dir ../docs
      working-directory: ./3DConsturctor-Intro

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ../docs
        git commit -m 'Deploy MkDocs site to GitHub Pages'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}